# Site settings
title: My Journey Through Code
header-img: img/home-bg.png
email: victoriamachen@gmail.com
copyright_name: machen2
description: > # this means to ignore newlines until "baseurl:"
  </>
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  machen2
learn_profile: machen2
email_username: victoriamachen@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
